# Generated by Django 4.0.1 on 2022-01-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hero_image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
